### ISSUE TITLE
Use basepython env param by default

### ISSUE THREAD

**Issue by voronind** [tox-dev/tox-travis#111]
We have config:
```ini
[tox]
envlist = py35, py36, docs
skipsdist = true

[testenv]
skip_install = true
commands = python --version

[testenv:docs]
basepython = python3.5
```
When we run `tox` locally we get 3 tests. And `docs` will run with `basepython` python.
When we run `tox` on travis we don't run 'docs' test on Python 3.5.
I know that i can do `[travis] python = 3.5: py35, docs`,
but maybe it will useful have this behavior by default?

**Comment by ryanhiebert** [comment]
It's a little to magical for my taste, but if you name the `docs` env as `py35-docs`, then it will, by default, run everything with a part of `py35` in it, so it would run both `py35` and `py35-docs`. How does that sound to you?

**Comment by ryanhiebert** [comment]
I've given it further thought, and I would be good with adding this method of choosing the Python version that an env should run under. I'm not sure how invasive of a change it would be, and I'm not ready to write it myself, but I'd be happy to entertain pull requests for this.

**Comment by rpkilby** [comment]
Gut reaction - I'm kind of -1 on implicitly matching on `basepython`. I typically use separate Travis jobs for auxiliary checks (e.g., linting, docs, readme), and wouldn't want these to be automatically lumped in with the default py* factors.

That said, maybe some additional option for matching on a factor? e.g., 

```ini
[testenv:docs]
basepython = python3.5
travis_factor = py35
```

Thoughts?

**Comment by ryanhiebert** [comment]
@rpkilby: you're absolutely right, I do that all the time as well, so this would not be a good experience for me, and assumably others. Now that I see your objection, I'd even consider this idea a breaking change. So I'm definitely convinced the original approach is unworkable.

I'm not a fan of the alternative you suggested either, because it seems icky to be putting stuff in the tox config sections. But if there's no particular issues from tox, that may be reasonable.

I think I'd be okay with that, but that would still be a pull request, because I don't care about it enough to do it myself. I'm happy with the status quo on this.

**Comment by rpkilby** [comment]
I assume it's acceptable to put our own config in the main tox section. Otherwise, it would be more difficult to do per-testenv customization. I think the main concern is making sure the keys don't conflict with tox or another plugin, so we would have to prefix the keys with something like `travis_`.

I also don't particularly like the `travis_factor` option, since you would need to read each testenv config to figure out what is being mapped to a particular factor. I'd be more in favor with the status quo, which puts the config all in one place.

**Comment by ryanhiebert** [comment]
Sounds good. Status quo it is!
