### ISSUE TITLE
pypy3 fix for missing expected binary

### ISSUE THREAD

**Issue by jayvdb** [tox-dev/tox-travis#28]
I am pretty confident we can provide a fixup for https://github.com/travis-ci/travis-ci/issues/6304 , which looks like the cause of https://github.com/travis-ci/travis-ci/issues/4306 .

**Comment by ryanhiebert** [comment]
Is this just a matter of making a pypy3 symlink to the python on the path? How do we know where to create the symlink, and which python to point it at? And would this remove the need for the pypy3 5.2 hack we have in the code currently?

I'm certainly in favor of this approach, it seems like a good one to me.

**Comment by ryanhiebert** [comment]
@jayvdb : Do you think you'll be able to look at this one? If not, it seems like things are working, so I'd probably end up closing this issue.

**Comment by ryanhiebert** [comment]
If anyone comes across this issue wondering why it's closed, it's because the hack that we already have in place for PyPy3 seems to be working pretty well. I'm still open to this approach, if anyone becomes interested in helping me identify exactly what we should do and helping me to test to make sure the solution works.
