### ISSUE TITLE
Please note the discussion in the tox project

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox-travis#74]
Hi, sorry for cluttering your issues, but I would like to note that we are discussing ways of better Travis integration for tox and we look at different options. This project has been mentioned there, so I would like to invite you to join the exchange.

Export support for travis: https://github.com/tox-dev/tox/issues/562

**Comment by obestwalter** [comment]
Also: moving the project into the org would be something worth discussing?

**Comment by rpkilby** [comment]
Hi @obestwalter - I've subscribed to the issue and am happy to weigh in when the discussion is revived.

**Comment by ryanhiebert** [comment]
Thank you for the heads up. I also have subscribed to the thread, and am happy to be a part of any discussion and work toward making the integration better, including coming up with a new system, or fixing the issues with this project.

And I would absolutely be willing to have this be in the tox-dev organization, if it was something that organization was willing to put their name on. For now, its my name here, and any problems or bad design are reflections on me, rather than on Tox, and perhaps that's a good thing. I'd hate to have any shoddy design on my part mar the name of another project, though I have attempted to do the best I can with this project, and am proud of the modest success it has gained.

**Comment by obestwalter** [comment]
Hey @ryanhiebert good points. We definitely have to make clear what is part of the core and that authorship or responsibility for the project does not change just by being moved into the org. This needs a bit of discussion and some updates to the documentation. We can take a page out of the bug how pytest does it with their plugin ecosystem - they have some official plugins and they have third party plugins, but they also try to keep all of them in the org AFAIK. Regardless of where the project lives: the original authors/teams keep the ownership and responsibilty to their projects just like before but with the adavantage that everything is in one place, giving better visibility to the projects and the chance that the memers of the different projects can help each other out.

**Comment by ryanhiebert** [comment]
Does anyone have a problem with this repository being moved to the tox-dev org? I've been added as a member there, and I'm inclined to go ahead and move it.

**Comment by rpkilby** [comment]
I don't have an issue with it.

**Comment by obestwalter** [comment]
Great news. I started adressing your points by shamelessly copying the policy that pytest using in the onging docs cleanup: https://github.com/tox-dev/tox/pull/636/files#diff-ea1f65a8eaac0cec7ae151dfdbbbc587R189

**Comment by obestwalter** [comment]
So if this is something you can get behind, press the transfer button, otherwise let us know and we'll discuss it.

**Comment by ryanhiebert** [comment]
The button is pressed, and I've already subscribed to the conversation that opened this issue. Thanks @obestwalter !

**Comment by obestwalter** [comment]
Welcome to the team/family then :D
