### ISSUE TITLE
Deprecation of matching undeclared envs

### ISSUE THREAD

**Issue by jayvdb** [tox-dev/tox-travis#97]
Apparently we're deprecating a feature I often use, or more likely something else is slightly off.

see https://github.com/vstinner/faulthandler/pull/33/commits/957915c23441a262cd2ee35c667a3dfcaf3b6624 , for adding testing of an environment that *is* declared by tox.  `py26` is a part of the standard `tox` environment list.

However this results in:

> Matching undeclared envs is deprecated. Be sure all the envs that Tox should run are declared in the tox config.

Build showing problem at
https://travis-ci.org/vstinner/faulthandler/jobs/304196356#L487

Irrespective of anything else, there is a very good reason to not require any modification to `tox.ini`.
Many people want `tox-travis` to be only a travis thing, and not need further configuration that they need to see.  Travis testing can include environments that they do not want to see in `tox.ini`, because they dont want `tox` on their workstation to know about (and try to run) non-standard environments.
If `tox-travis` requires modifications to `tox.ini`, you loose users, because they are opinionated about `tox.ini`, but not opinionated about `.travis.yml` as long as it does the job.

**Comment by ryanhiebert** [comment]
Thank you for opening this. I've been thinking about it the past day or so, and I've been questioning exactly what we do and don't want to do in this regard, so thank you for confirming that there's something here that we need to be careful with.

I'll be posting back here in a little bit with some possibilities for how we can handle this as gracefully as possible, and all the trade-offs associated with the options, but I wanted to note before I took the time to figure those possibilities out that I have registered the concern, I have already shared it previously, and that I intend to be very careful with how I deal with this.

**Comment by rpkilby** [comment]
@ryanhiebert - would this not be covered by the strict option?

**Comment by ryanhiebert** [comment]
The strict mode is what this is about, and why the deprecation notice even exists. It was my intention to enforce this, but this isn't gonna be a good idea. I'm working on a longer response to this issue, but I've been busy today and haven't been able to finish it just yet.

**Comment by ryanhiebert** [comment]
> see vstinner/faulthandler@957915c , for adding testing of an environment that is declared by tox. py26 is a part of the standard tox environment list.

This is an interesting assessment, that doesn't line up with the way that I have looked at it in the past. The `py26` *factor* is part of the standard tox setup, but the env itself doesn't really exist yet, in the same way that if you would configure factors `dj18` and `dj19` to install Django versions 1.8 and 1.9 respectively, but don't put them in the envlist, the `dj18` and `dj19` factors won't run either.

Still, Tox allows envs to run that aren't declared in the configuration by just configuring them the best it can, the same as it does when envs are put in the envlist, matching whatever factors it finds; in this case, the `pyXX` factor you've specified.

This makes me wonder if tox factors that are configured in the tox config, but don't have matching envs, should in general be allowed to run without declaring any specific matching env. Unfortunately, there are complications with that idea that I'm not sure if there are good ways to handle when we start considering matching multiple factors.

For example, what do we do when there are matches, or when the order is ambiguous? If we have configured `dj17` and `py36`, should the variants combine to make a guess of `dj17-py36` or `py36-dj17`. AFAIK, the order does matter to Tox, because it might have a section for it (i.e. `[testenv:py36-dj17]`) and the section won't match if the factors aren't in the right order. Also, what should happen if there's a match for `py36-dj17-spam`, but `py36-dj17` isn't declared? Should `py36-dj17` run as well, or would it be excluded?

My inclination is that so much of this doesn't make sense when generalized that it's really only applicable to 1 factor in that mode.

-----------

> If tox-travis requires modifications to tox.ini, you lose users, because they are opinionated about tox.ini, but not opinionated about .travis.yml as long as it does the job.

Tox-Travis has its configuration in sections of the `tox.ini`. Are you suggesting even that isn't a good enough separation? I hope not, because we can't put stuff in the `.travis.yml` (we just detect the stuff that Travis does with it), and I don't see a better file to put the configuration in. Other tools, like coverage and flake8 also allow their configuration in the `tox.ini`.

I suspect that what you're meaning here is that external tools, like Tox-Travis, shouldn't require changes to the Tox configuration (the specific parts of `tox.ini` that Tox actually uses for its configuration). Since our configuration is segregated into separate sections that include `travis` at the beginning, I'm hoping that you will confirm that you think that is a sufficient separation from the standard Tox configuration.

If I'm right about all that, then the primary problem that you're pointing out is that this deprecation requires changing the Tox configuration. I agree.

-------------

So, having resolved that Tox-Travis should not require any changes to the standard Tox configuration in order to operate, I believe that we have a setting that desperately needs to be added: `envlist`. This setting will act just like the Tox `envlist`, including expansion, and it will declare all of the envs that Tox-Travis may consider when choosing which envs to run.

I believe that this setting should default to the Travis `envlist`, plus additional envs specified as `[testenv:XXX]` sections, plus automatic sections for the `pyXX` envs that are easily auto-configured because of Tox's default handling of those factors. I also think that this will resolve all of the contention brought up in this issue, because undeclared `pyXX` envs will still be able to be run without addition configuration.

This alone will require keeping the hack that adds the envconfigs to Tox during the Tox-Configure hook. I'm OK with that, and I'll likely open an issue on Tox to allow us a public method that we can use to do that without so much copy and paste of internal code and monkeypatching. But the first priority is to make Tox-Travis work the way that it should.

-------------

This doesn't do away with the deprecation entirely, though, because the deprecation also covers a even more special case: undeclared and non-standard envs. For example, right now this configuration will pass through an envlist including `py36` and `docs`, even though `docs` doesn't exist:

```yaml
language: python
python: 3.6
install: pip install tox-travis
script: tox
```

```ini
[tox]
envlist = py36

[travis]
python =
    3.6: py36, docs
```

It works this way, because the original version of Tox-Travis, before we introduced factor-matching, simply passed the string along in the `TOXENV` environment variable, and Tox did what it does with any envlist, and creates any missing envs.

What I'd like to be able to do is raise an error if somebody tries to run `docs` in this case, since it's both non-standard and undeclared.

Would that smaller breaking change be acceptable? It's the real goal of the deprecation, even though it ended up pulling in more than that. I want to be able to eliminate this odd passthru behavior that is a wart of the original release of Tox-Travis.
